apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pizzaproject.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pizzaproject.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "pizzaproject.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "{{ .Values.application.env }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "pizzaproject.fullname" . }}
                  key: djangoSecretKey
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - mountPath: /app/db
              name: sqlite-storage
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc