# Generated by Django 5.0.7 on 2024-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzatype', models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Vegetarian,', 'Vegetarian')], max_length=100)),
                ('commentorder', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
