name: Deploy artifact to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: |
        cd pizzaproject
        docker build . -t trebol256/pizzaproject:latest
        docker push trebol256/pizzaproject:latest

    # - name: Deploy to Kubernetes
    #   env:
    #     DJANGO_SECRET_KEY: {{ secrets.DJANGO_SECRET_KEY }}
    #   run: |
    #       cd helm
    #       helm install prod . --set secret.djangoSecretKey=$DJANGO_SECRET_KEY